from aenum import IntEnum


class ErrorCode(IntEnum):
    """
    Enum for Errors codes generated by this server to be sent to Kubos OBC"

    """

    # No error was encountered
    Ok = 0x00
    # Unknown command received
    UnknownCommand = 0x01
    # Supplied data incorrect when processing command
    CommandDataIncorrect = 0x02
    # Selected channel does not exist
    CommandIncomplete = 0x03
    # Selected channel is currently inactive
    ChannelInactive = 0x04
    # CRC code does not match data
    BadCRC = 0x10
    # A reset had to occur
    ResetOccurred = 0x13
    # There was an error with the ADC acquisition
    ImageIndexNotValid = 0x14
    # Reading from EEPROM generated an error
    FailReadingEEPROM = 0x20
    # Generic warning about an error on the internal SPI bus
    InternalSPIError = 0x30
    # The command to fetch the last error failed
    CommandError = 0xFF
